layout_spectrum: 0.4784098
color:
  saturation: 0.3715697
  brandStrength: 0.2406235
  lightness: 0.4510863
  brandColors:
    - '#256A93'
    - '#FFFFFF'
    - '#020202'
    - '#B5B4B4'
    - '#5C5C5C'
  rhythmicContrast: 0.8056685
typography_spectrum: 0.8712866
name: Healthfultips
